#
# Usage:
#   conda env create --file=.conda/environment.yml -n rbc-dev
#   python setup.py develop
#   pytest -sv .

name: rbc
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3
  - setuptools
  - numba
  - llvmlite
  - pytest
  - tblib
  - thriftpy2
  - netifaces
  - clang
  - six
  # - cudatoolkit-dev   # disable temporary
