#
# Usage:
#   conda env create --file=.conda/environment.yml -n rbc-dev
#   python setup.py develop
#   pytest -sv .

name: rbc
channels:
  - conda-forge
  - defaults
dependencies:
  #- gcc_linux-64    # required for building thriftpy2
  - c-compiler
  # - gxx_linux-64
  - setuptools
  - pip
  - numba
  - llvmlite>=0.28
  - pytest
  - tblib
  - pymapd
  # - cudatoolkit-dev   # disable temporary
