#
# Usage:
#   conda env create --file=.conda/environment.yml -n rbc-dev
#   python setup.py develop
#   pytest -sv .

name: rbc
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3
  #- c-compiler
  - setuptools
  #- pip
  - numba
  - llvmlite>=0.29
  - pytest
  - tblib
  - pymapd
  - thriftpy2
  - netifaces
  - ply
  - flake8
  # - cudatoolkit-dev   # disable temporary
