name: rbc
channels:
  - conda-forge
dependencies:
  - gcc_linux-64    # required for building thriftpy2
  # - gxx_linux-64
  - setuptools
  - pip
  - numba
  - llvmlite>=0.28
  - pytest
  - tblib
  - pymapd
  # - cudatoolkit-dev   # disable temporary
